/**
 * This class implements Java's built-in random number generator.
 */
public class JavaRNG implements DoubleRNG {

	private int length;

	public JavaRNG(int length) {
		this.length = length;
	}

	// Returns a list of pseudo random numbers generated by Java's RNG.
	public double[] output() {
		double[] result = new double[length];
		for (int i = 0; i != length; i++) {
			result[i] = Math.random();
		}
		return result;
	}

	// Calculates the estimated area of a quadrant.
	public double ratio(double[] n) {
		int count = 0;
		for (int i = 0; i != n.length - 1; i++) {
			if ((n[i] * n[i] + n[i + 1] * n[i + 1]) <= 1.0) {
				count++;
			}
		}
		return (double) count / (n.length - 1);
	}
}
