/**
 * This class provides utility functions for a Lehmer's random number generator.
 */
public class LehmerRNG implements IntegerRNG {

	private int length;
	private int seed;
	private int m;
	private int a;
	private int c;

	public LehmerRNG(int length, int seed, int m, int a, int c) {
		this.length = length;
		this.seed = seed;
		this.m = m;
		this.a = a;
		this.c = c;
	}

	// Returns a list of pseudo random numbers generated by a Lehmer's RNG using the
	// user-specified parameters.
	public int[] output() {
		int[] result = new int[length];
		result[0] = seed;
		for (int i = 0; i != length; i++) {
			if (i == 0) {
				result[0] = (a * seed + c) % m;
			} else {
				result[i] = (a * result[i - 1] + c) % m;
			}
		}
		return result;
	}

	// Calculates the estimated area of a quadrant. 
	public double ratio(int[] n) {
		int count = 0;
		double first;
		double second;
		for (int i = 0; i != n.length - 1; i++) {
			first = (double) n[i] / m;
			second = (double) n[i + 1] / m;

			if (first * first + second * second <= 1) {
				count++;
			}
		}
		return (double) count / (n.length - 1);
	}
}
